const Reservation = require("../Model/ReservationModel");
const Seat = require("../Model/SeatModel");

//CREATE
const createReservation = async (req, res) => {
  try {
    const { 
      studentID, 
      busID, 
      seatNumber, 
      reservationType, 
      startDate, 
      endDate, 
      daysBooked, 
      seasonType 
    } = req.body;

    // Find the seat by busID and seatNumber
    const seat = await Seat.findOne({ busID, seatNumber });
    if (!seat) return res.status(404).json({ error: "Seat not found" });
    if (seat.status !== "Available")
      return res.status(400).json({ error: "Seat is not available" });

    // Calculate fee based on reservation type
    let feeAmount = 0;
    let feeBreakdown = {
      registrationFee: 100, // Base registration fee
      monthlyFee: 0,
      annualFee: 0,
      dailyFee: 0
    };

    if (reservationType === "Regular") {
      if (seasonType === "Monthly") {
        feeBreakdown.monthlyFee = 2500;
        feeAmount = feeBreakdown.registrationFee + feeBreakdown.monthlyFee;
      } else if (seasonType === "Annual") {
        feeBreakdown.annualFee = 25000;
        feeAmount = feeBreakdown.registrationFee + feeBreakdown.annualFee;
      }
    } else if (reservationType === "Temporary") {
      feeBreakdown.dailyFee = 150 * (daysBooked || 1);
      feeAmount = feeBreakdown.registrationFee + feeBreakdown.dailyFee;
    }

    // Mark seat as pending
    seat.status = "Reserved";
    await seat.save();

    // Create reservation (reservationID will be auto-generated by pre-save hook)
    const reservation = new Reservation({
      studentID,
      busID,
      seatNumber,
      reservationType,
      startDate: new Date(startDate),
      endDate: endDate ? new Date(endDate) : undefined,
      daysBooked: reservationType === "Temporary" ? daysBooked : undefined,
      feeAmount,
      feeBreakdown,
      paymentStatus: "Pending",
      status: "Pending",
      seasonType: reservationType === "Regular" ? seasonType : undefined
    });

    await reservation.save();

    res.status(201).json({
      message: "Reservation created - Please proceed to payment",
      reservation,
      requiresPayment: true
    });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};

//READ (by student)
const getReservationsByStudent = async (req, res) => {
  try {
    const { studentID } = req.params;
    const reservations = await Reservation.find({ studentID }).sort({ createdAt: -1 });
    res.json(reservations);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};

//UPDATE RESERVATION STATUS (Payment Simulation Result)
const updateReservationStatus = async (req, res) => {
  try {
    const { id } = req.params;
    const { status, paymentStatus } = req.body;

    // Validate status values
    if (!["Booked", "Cancelled"].includes(status)) {
      return res.status(400).json({ error: "Invalid status. Use 'Booked' or 'Cancelled'" });
    }

    const reservation = await Reservation.findById(id);
    if (!reservation) return res.status(404).json({ error: "Reservation not found" });

    // Update reservation status and payment status
    reservation.status = status;
    reservation.paymentStatus = paymentStatus || (status === "Booked" ? "Success" : "Failed");
    await reservation.save();

    // Update seat status based on payment result
    if (status === "Booked") {
      await Seat.findOneAndUpdate(
        { busID: reservation.busID, seatNumber: reservation.seatNumber }, 
        { status: "Booked" }
      );
      res.json({ 
        message: "Payment successful - Seat booked!", 
        reservation,
        paymentStatus: "success"
      });
    } else if (status === "Cancelled") {
      await Seat.findOneAndUpdate(
        { busID: reservation.busID, seatNumber: reservation.seatNumber }, 
        { status: "Available" }
      );
      res.json({ 
        message: "Payment failed - Reservation cancelled", 
        reservation,
        paymentStatus: "failed"
      });
    }

  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};

//UPDATE (approve / cancel) - For admin use
const updateReservation = async (req, res) => {
  try {
    const { id } = req.params;
    const { status } = req.body;

    const reservation = await Reservation.findById(id);
    if (!reservation) return res.status(404).json({ error: "Reservation not found" });

    reservation.status = status;
    await reservation.save();

    if (status === "Booked") {
      await Seat.findOneAndUpdate(
        { busID: reservation.busID, seatNumber: reservation.seatNumber }, 
        { status: "Booked" }
      );
    }
    if (status === "Cancelled") {
      await Seat.findOneAndUpdate(
        { busID: reservation.busID, seatNumber: reservation.seatNumber }, 
        { status: "Available" }
      );
    }

    res.json({ message: "Reservation updated", reservation });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};

//DELETE
const deleteReservation = async (req, res) => {
  try {
    const { id } = req.params;
    const reservation = await Reservation.findById(id);
    if (!reservation) return res.status(404).json({ error: "Reservation not found" });

    // Free seat back to available
    await Seat.findOneAndUpdate(
      { busID: reservation.busID, seatNumber: reservation.seatNumber }, 
      { status: "Available" }
    );

    await reservation.deleteOne();

    res.json({ message: "Reservation deleted" });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};

module.exports = {
  createReservation,
  getReservationsByStudent,
  updateReservationStatus,
  updateReservation,
  deleteReservation,
};
