const mongoose = require("mongoose");

const waitlistSchema = new mongoose.Schema({
  waitlistID: {
    type: String,
    required: false, // Auto-generated by pre-save hook
    unique: true,
    trim: true
  },
  studentID: {
    type: String,
    required: true,
    trim: true
  },
  busID: {
    type: String,
    required: true
  },
  routeID: {
    type: String,
    required: true
  },
  studentType: {
    type: String,
    enum: ["Regular", "Temporary"],
    required: true
  },
  priority: {
    type: Number,
    default: 0 // Higher number = higher priority, Regular students get higher priority
  },
  requestedDate: {
    type: Date,
    required: true
  },
  expectedDuration: {
    type: Number, // Days for temporary students
    required: function() {
      return this.studentType === "Temporary";
    }
  },
  seasonType: {
    type: String,
    enum: ["Monthly", "Annual"],
    required: function() {
      return this.studentType === "Regular";
    }
  },
  status: {
    type: String,
    enum: ["Active", "Fulfilled", "Cancelled", "Expired"],
    default: "Active"
  },
  notificationSent: {
    type: Boolean,
    default: false
  },
  createdAt: {
    type: Date,
    default: Date.now
  },
  updatedAt: {
    type: Date,
    default: Date.now
  },
  expiresAt: {
    type: Date,
    default: function() {
      // Waitlist entries expire after 30 days if not fulfilled
      return new Date(Date.now() + 30 * 24 * 60 * 60 * 1000);
    }
  }
});

// Generate unique waitlist ID
waitlistSchema.pre('save', function(next) {
  if (!this.waitlistID) {
    this.waitlistID = 'WL' + Date.now() + Math.floor(Math.random() * 1000);
  }
  
  // Set priority based on student type
  if (this.studentType === "Regular") {
    this.priority = 100; // Higher priority for regular students
  } else {
    this.priority = 50; // Lower priority for temporary students
  }
  
  this.updatedAt = Date.now();
  next();
});

// Index for efficient querying
waitlistSchema.index({ busID: 1, status: 1, priority: -1, createdAt: 1 });
waitlistSchema.index({ studentID: 1 });
waitlistSchema.index({ expiresAt: 1 }, { expireAfterSeconds: 0 });

module.exports = mongoose.model("Waitlist", waitlistSchema);